### PR TITLE
Improve ProbOnto import in DKG

### PR DESCRIPTION
**Pull request by cthoyt**
This PR looks into `probonto` and gets probability distributions, their parameters, and a list of equivalent distributions (that have been reparemetrized):

```json
{
    "curie": "probonto:k0001091",
    "name": "Student's t-distribution 3",
    "equivalent": [
      {
        "curie": "probonto:k0000635",
        "name": "Student's t-distribution 2"
      }
    ],
    "parameters": [
      {
        "curie": "probonto:k0001095",
        "name": "scale of Student-s-t-distribution-3",
        "symbol": "\\sigma",
        "short_name": "scale"
      },
      {
        "curie": "probonto:k0001093",
        "name": "degrees of freedom of Student-s-t-distribution-3",
        "symbol": "\\nu",
        "short_name": "degrees of freedom"
      },
      {
        "curie": "probonto:k0001094",
        "name": "mean of Student-s-t-distribution-3",
        "symbol": "\\mu",
        "short_name": "mean"
      }
    ]
  },
...
```

### CODE REVIEW

**Comment by cthoyt** [comment]
@bgyori should I group the different parametrizations of the same distribution?

**Comment by bgyori** [comment]
I think ultimately the different parameterizations have to be maintained as separate object. However, representing the parent distribution of which they are specific parameterizations would also be useful. Does ProbOnto provide these parent classes e.g., for the different instances of the negative binomial distribution?

**Comment by cthoyt** [comment]
No, it does not provide a class that groups these. Perhaps I could make that as a contribution

**Comment by cthoyt** [comment]
I made a solution that deconstructs some relationships that are themselves encoded in individuals to map between different parameterizations of the same distribution. This should be ready.

**Review by bgyori — APPROVED** [review]

**Pull request merged**
